/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (server-fsm.c)
 *
 *  It has been AutoGen-ed
 *  From the definitions    server.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2018 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define DEFINE_FSM
#include "server-fsm.h"
#include <stdio.h>

/*
 *  Do not make changes to this file, except between the START/END
 *  comments, or it will be removed the next time it is generated.
 */
/* START === USER HEADERS === DO NOT CHANGE THIS COMMENT */
/* END   === USER HEADERS === DO NOT CHANGE THIS COMMENT */

#ifndef NULL
#  define NULL 0
#endif

/**
 *  Enumeration of the valid transition types
 *  Some transition types may be common to several transitions.
 */
typedef enum {
    SMTP_SERVER_FSM_TR_DATA_CFAIL,
    SMTP_SERVER_FSM_TR_DATA_RSET,
    SMTP_SERVER_FSM_TR_DATA_TEXT,
    SMTP_SERVER_FSM_TR_INIT_S_CFAIL,
    SMTP_SERVER_FSM_TR_INIT_S_EHLO,
    SMTP_SERVER_FSM_TR_INIT_S_HELO,
    SMTP_SERVER_FSM_TR_INVALID,
    SMTP_SERVER_FSM_TR_MAIL_CFAIL,
    SMTP_SERVER_FSM_TR_MAIL_RCPT,
    SMTP_SERVER_FSM_TR_MAIL_RSET,
    SMTP_SERVER_FSM_TR_RCPT_CFAIL,
    SMTP_SERVER_FSM_TR_RCPT_DATA,
    SMTP_SERVER_FSM_TR_RCPT_RCPT,
    SMTP_SERVER_FSM_TR_RCPT_RSET,
    SMTP_SERVER_FSM_TR_TEXT_CFAIL,
    SMTP_SERVER_FSM_TR_TEXT_MAIL,
    SMTP_SERVER_FSM_TR_TEXT_QUIT,
    SMTP_SERVER_FSM_TR_TEXT_RSET,
    SMTP_SERVER_FSM_TR_WAIT_CFAIL,
    SMTP_SERVER_FSM_TR_WAIT_MAIL,
    SMTP_SERVER_FSM_TR_WAIT_RSET
} te_smtp_server_fsm_trans;
#define SMTP_SERVER_FSM_TRANSITION_CT  21

/**
 *  State transition handling map.  Map the state enumeration and the event
 *  enumeration to the new state and the transition enumeration code (in that
 *  order).  It is indexed by first the current state and then the event code.
 */
typedef struct smtp_server_fsm_transition t_smtp_server_fsm_transition;
struct smtp_server_fsm_transition {
    te_smtp_server_fsm_state  next_state;
    te_smtp_server_fsm_trans  transition;
};
static const t_smtp_server_fsm_transition
smtp_server_fsm_trans_table[ SMTP_SERVER_FSM_STATE_CT ][ SMTP_SERVER_FSM_EVENT_CT ] = {

  /* STATE 0:  SMTP_SERVER_FSM_ST_INIT */
  { { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  HELO */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  EHLO */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  MAIL */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  RCPT */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  DATA */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  RSET */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  QUIT */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  CFAIL */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID } /* EVT:  TEXT */
  },


  /* STATE 1:  SMTP_SERVER_FSM_ST_INIT_S */
  { { SMTP_SERVER_FSM_ST_WAIT, SMTP_SERVER_FSM_TR_INIT_S_HELO }, /* EVT:  HELO */
    { SMTP_SERVER_FSM_ST_WAIT, SMTP_SERVER_FSM_TR_INIT_S_EHLO }, /* EVT:  EHLO */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  MAIL */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  RCPT */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  DATA */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  RSET */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  QUIT */
    { SMTP_SERVER_FSM_ST_CLOSE, SMTP_SERVER_FSM_TR_INIT_S_CFAIL }, /* EVT:  CFAIL */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID } /* EVT:  TEXT */
  },


  /* STATE 2:  SMTP_SERVER_FSM_ST_WAIT */
  { { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  HELO */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  EHLO */
    { SMTP_SERVER_FSM_ST_MAIL, SMTP_SERVER_FSM_TR_WAIT_MAIL }, /* EVT:  MAIL */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  RCPT */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  DATA */
    { SMTP_SERVER_FSM_ST_WAIT, SMTP_SERVER_FSM_TR_WAIT_RSET }, /* EVT:  RSET */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  QUIT */
    { SMTP_SERVER_FSM_ST_CLOSE, SMTP_SERVER_FSM_TR_WAIT_CFAIL }, /* EVT:  CFAIL */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID } /* EVT:  TEXT */
  },


  /* STATE 3:  SMTP_SERVER_FSM_ST_MAIL */
  { { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  HELO */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  EHLO */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  MAIL */
    { SMTP_SERVER_FSM_ST_RCPT, SMTP_SERVER_FSM_TR_MAIL_RCPT }, /* EVT:  RCPT */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  DATA */
    { SMTP_SERVER_FSM_ST_WAIT, SMTP_SERVER_FSM_TR_MAIL_RSET }, /* EVT:  RSET */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  QUIT */
    { SMTP_SERVER_FSM_ST_CLOSE, SMTP_SERVER_FSM_TR_MAIL_CFAIL }, /* EVT:  CFAIL */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID } /* EVT:  TEXT */
  },


  /* STATE 4:  SMTP_SERVER_FSM_ST_RCPT */
  { { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  HELO */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  EHLO */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  MAIL */
    { SMTP_SERVER_FSM_ST_RCPT, SMTP_SERVER_FSM_TR_RCPT_RCPT }, /* EVT:  RCPT */
    { SMTP_SERVER_FSM_ST_DATA, SMTP_SERVER_FSM_TR_RCPT_DATA }, /* EVT:  DATA */
    { SMTP_SERVER_FSM_ST_WAIT, SMTP_SERVER_FSM_TR_RCPT_RSET }, /* EVT:  RSET */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  QUIT */
    { SMTP_SERVER_FSM_ST_CLOSE, SMTP_SERVER_FSM_TR_RCPT_CFAIL }, /* EVT:  CFAIL */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID } /* EVT:  TEXT */
  },


  /* STATE 5:  SMTP_SERVER_FSM_ST_DATA */
  { { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  HELO */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  EHLO */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  MAIL */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  RCPT */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  DATA */
    { SMTP_SERVER_FSM_ST_WAIT, SMTP_SERVER_FSM_TR_DATA_RSET }, /* EVT:  RSET */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  QUIT */
    { SMTP_SERVER_FSM_ST_CLOSE, SMTP_SERVER_FSM_TR_DATA_CFAIL }, /* EVT:  CFAIL */
    { SMTP_SERVER_FSM_ST_TEXT, SMTP_SERVER_FSM_TR_DATA_TEXT } /* EVT:  TEXT */
  },


  /* STATE 6:  SMTP_SERVER_FSM_ST_CLOSE */
  { { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  HELO */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  EHLO */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  MAIL */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  RCPT */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  DATA */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  RSET */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  QUIT */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  CFAIL */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID } /* EVT:  TEXT */
  },


  /* STATE 7:  SMTP_SERVER_FSM_ST_TEXT */
  { { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  HELO */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  EHLO */
    { SMTP_SERVER_FSM_ST_MAIL, SMTP_SERVER_FSM_TR_TEXT_MAIL }, /* EVT:  MAIL */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  RCPT */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID }, /* EVT:  DATA */
    { SMTP_SERVER_FSM_ST_WAIT, SMTP_SERVER_FSM_TR_TEXT_RSET }, /* EVT:  RSET */
    { SMTP_SERVER_FSM_ST_CLOSE, SMTP_SERVER_FSM_TR_TEXT_QUIT }, /* EVT:  QUIT */
    { SMTP_SERVER_FSM_ST_CLOSE, SMTP_SERVER_FSM_TR_TEXT_CFAIL }, /* EVT:  CFAIL */
    { SMTP_SERVER_FSM_ST_INVALID, SMTP_SERVER_FSM_TR_INVALID } /* EVT:  TEXT */
  }
};


#define Smtp_Server_FsmFsmErr_off     19
#define Smtp_Server_FsmEvInvalid_off  75
#define Smtp_Server_FsmStInit_off     83


static char const zSmtp_Server_FsmStrings[152] =
/*     0 */ "** OUT-OF-RANGE **\0"
/*    19 */ "FSM Error:  in state %d (%s), event %d (%s) is invalid\n\0"
/*    75 */ "invalid\0"
/*    83 */ "init\0"
/*    88 */ "init_s\0"
/*    95 */ "wait\0"
/*   100 */ "mail\0"
/*   105 */ "rcpt\0"
/*   110 */ "data\0"
/*   115 */ "close\0"
/*   121 */ "text\0"
/*   126 */ "helo\0"
/*   131 */ "ehlo\0"
/*   136 */ "rset\0"
/*   141 */ "quit\0"
/*   146 */ "cfail";

static const size_t aszSmtp_Server_FsmStates[8] = {
    83,  88,  95,  100, 105, 110, 115, 121 };

static const size_t aszSmtp_Server_FsmEvents[10] = {
    126, 131, 100, 105, 110, 136, 141, 146, 121, 75 };


#define SMTP_SERVER_FSM_EVT_NAME(t)   ( (((unsigned)(t)) >= 10) \
    ? zSmtp_Server_FsmStrings : zSmtp_Server_FsmStrings + aszSmtp_Server_FsmEvents[t])

#define SMTP_SERVER_FSM_STATE_NAME(s) ( (((unsigned)(s)) >= 8) \
    ? zSmtp_Server_FsmStrings : zSmtp_Server_FsmStrings + aszSmtp_Server_FsmStates[s])

#ifndef EXIT_FAILURE
# define EXIT_FAILURE 1
#endif

static int smtp_server_fsm_invalid_transition( te_smtp_server_fsm_state st, te_smtp_server_fsm_event evt );

/* * * * * * * * * THE CODE STARTS HERE * * * * * * * */
/**
 *  Print out an invalid transition message and return EXIT_FAILURE
 */
static int
smtp_server_fsm_invalid_transition( te_smtp_server_fsm_state st, te_smtp_server_fsm_event evt )
{
    /* START == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */
    char const * fmt = zSmtp_Server_FsmStrings + Smtp_Server_FsmFsmErr_off;
    fprintf( stderr, fmt, st, SMTP_SERVER_FSM_STATE_NAME(st), evt, SMTP_SERVER_FSM_EVT_NAME(evt));
    /* END   == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */

    return EXIT_FAILURE;
}

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  SMTP_SERVER_FSM_ST_DONE or SMTP_SERVER_FSM_ST_INVALID, it resets to
 *  SMTP_SERVER_FSM_ST_INIT and returns SMTP_SERVER_FSM_ST_INIT.
 */
te_smtp_server_fsm_state
smtp_server_fsm_step(
    te_smtp_server_fsm_state smtp_server_fsm_state,
    te_smtp_server_fsm_event trans_evt,
    void *data )
{
    te_smtp_server_fsm_state nxtSt;
    te_smtp_server_fsm_trans trans;

    if ((unsigned)smtp_server_fsm_state >= SMTP_SERVER_FSM_ST_INVALID) {
        return SMTP_SERVER_FSM_ST_INIT;
    }

#ifndef __COVERITY__
    if (trans_evt >= SMTP_SERVER_FSM_EV_INVALID) {
        nxtSt = SMTP_SERVER_FSM_ST_INVALID;
        trans = SMTP_SERVER_FSM_TR_INVALID;
    } else
#endif /* __COVERITY__ */
    {
        const t_smtp_server_fsm_transition * ttbl =
            smtp_server_fsm_trans_table[ smtp_server_fsm_state ] + trans_evt;
        nxtSt = ttbl->next_state;
        trans = ttbl->transition;
    }


    switch (trans) {
    case SMTP_SERVER_FSM_TR_DATA_CFAIL:
        /* START == DATA_CFAIL == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_DATA_CFAIL();
        /* END   == DATA_CFAIL == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_DATA_RSET:
        /* START == DATA_RSET == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_DATA_RSET();
        /* END   == DATA_RSET == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_DATA_TEXT:
        /* START == DATA_TEXT == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_DATA_TEXT();
        /* END   == DATA_TEXT == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_INIT_S_CFAIL:
        /* START == INIT_S_CFAIL == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_INIT_S_CFAIL();
        /* END   == INIT_S_CFAIL == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_INIT_S_EHLO:
        /* START == INIT_S_EHLO == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_INIT_S_EHLO();
        /* END   == INIT_S_EHLO == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_INIT_S_HELO:
        /* START == INIT_S_HELO == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_INIT_S_HELO();
        /* END   == INIT_S_HELO == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_INVALID:
        /* START == INVALID == DO NOT CHANGE THIS COMMENT */
        exit(smtp_server_fsm_invalid_transition(smtp_server_fsm_state, trans_evt));
        /* END   == INVALID == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_MAIL_CFAIL:
        /* START == MAIL_CFAIL == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_MAIL_CFAIL();
        /* END   == MAIL_CFAIL == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_MAIL_RCPT:
        /* START == MAIL_RCPT == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_MAIL_RCPT();
        /* END   == MAIL_RCPT == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_MAIL_RSET:
        /* START == MAIL_RSET == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_MAIL_RSET();
        /* END   == MAIL_RSET == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_RCPT_CFAIL:
        /* START == RCPT_CFAIL == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_RCPT_CFAIL();
        /* END   == RCPT_CFAIL == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_RCPT_DATA:
        /* START == RCPT_DATA == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_RCPT_DATA();
        /* END   == RCPT_DATA == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_RCPT_RCPT:
        /* START == RCPT_RCPT == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_RCPT_RCPT();
        /* END   == RCPT_RCPT == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_RCPT_RSET:
        /* START == RCPT_RSET == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_RCPT_RSET();
        /* END   == RCPT_RSET == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_TEXT_CFAIL:
        /* START == TEXT_CFAIL == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_TEXT_CFAIL();
        /* END   == TEXT_CFAIL == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_TEXT_MAIL:
        /* START == TEXT_MAIL == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_TEXT_MAIL();
        /* END   == TEXT_MAIL == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_TEXT_QUIT:
        /* START == TEXT_QUIT == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_TEXT_QUIT();
        /* END   == TEXT_QUIT == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_TEXT_RSET:
        /* START == TEXT_RSET == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_TEXT_RSET();
        /* END   == TEXT_RSET == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_WAIT_CFAIL:
        /* START == WAIT_CFAIL == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_WAIT_CFAIL();
        /* END   == WAIT_CFAIL == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_WAIT_MAIL:
        /* START == WAIT_MAIL == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_WAIT_MAIL();
        /* END   == WAIT_MAIL == DO NOT CHANGE THIS COMMENT */
        break;


    case SMTP_SERVER_FSM_TR_WAIT_RSET:
        /* START == WAIT_RSET == DO NOT CHANGE THIS COMMENT */
        nxtSt = HANDLE_WAIT_RSET();
        /* END   == WAIT_RSET == DO NOT CHANGE THIS COMMENT */
        break;


    default:
        /* START == BROKEN MACHINE == DO NOT CHANGE THIS COMMENT */
        exit(smtp_server_fsm_invalid_transition(smtp_server_fsm_state, trans_evt));
        /* END   == BROKEN MACHINE == DO NOT CHANGE THIS COMMENT */
    }


    /* START == FINISH STEP == DO NOT CHANGE THIS COMMENT */
    /* END   == FINISH STEP == DO NOT CHANGE THIS COMMENT */

    return nxtSt;
}
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of server-fsm.c */
